modules:
- audio_tasks
Tasks:
  MUSDB18Reader:
    class: AudioDatasetFromDirectory
    dataset_path: /home/lpepino/MUSDB18/wav
    parents_as_columns: #Use parent folders names as these columns
    - partition
    - song
    stem_as_column: instrument #Use filename as this column
  Framer:
    class: Framer
    in: MUSDB18Reader->out
    time_column: samples_count
    frame_size: 16384
    hop_size: 8192
    in_memory: True
  Mixer:
    class: Zipper
    in: Framer->out
    zip_by:
    - song
    - start
    columns:
    - filename
    - start
    - end
    - sampling_rate
    - instrument
  Partition:
    class: Split
    in: Mixer->out
    split_col: partition
    in_memory: True
  TrainGenerator:
    class: DeytahGenerator
    in: Partition->train
    deytah_config: deytah_configs/aligned_mix.yaml #Implementar incrustacion de configs
    deytah_x: mixture
    deytah_y: sources
    batch_size: 16
    in_memory: True
  DienenModel: #Implementar
    class: DienenModel
    in: TrainGenerator->out
    dienen_config: dienen_configs/dual_hp_cnn.yaml #Implementar -> modelo tesis, capas con pesos compartidos en dienen... y bloques de capas. Fun.



  
  




