defaults:
  loss: ls
  learning_rate: 0.1
  n_estimators: 100
  criterion: friedman_mse
  max_depth: 3
  max_features: null
RegressorModel:
  class: GradientBoostingMachineRegressor
  in: (in_task)->train
  target_col: quality
  features_col: null
  parameters:
    loss: !var loss
    learning_rate: !var learning_rate
    n_estimators: !var n_estimators
    criterion: !var criterion
    max_depth: !var max_depth
    max_features: !var max_features
