Model:
  name: dual_cnn
  Training:
    n_epochs: 20
    loss: mse
    Optimizer:
      type: Adam
      lr: 0.001
    Schedule:
      SaveCheckpoints:
        monitor_metric: loss
  Architecture:
  - Input:
      name: mixture_spectrogram
      shape: [1025,21,2]
      input: x
  - Log:
      name: logmag_stft
      base: 2
      offset: 1
  #PEncoder
  - Conv:
      name: PConv_0
      filters: 64
      kernel_size: [1025,1]
      activation: 'relu'
      use_bias: False
      batch_norm: True
  - Conv:
      name: PConv_1
      filters: 64
      kernel_size: [1,6]
      activation: 'relu'
      use_bias: False
      batch_norm: True
  - Flatten:
      name: PEmbedding
  #HEncoder
  - Conv:
      name: HConv_0
      filters: 32
      kernel_size: [1,21]
      activation: 'relu'
      use_bias: False
      batch_norm: True
      input: logmag_stft
  - Conv:
      name: HConv_1
      filters: 64
      kernel_size: [82,1]
      activation: 'relu'
      use_bias: False
      batch_norm: True
      strides: [41,1]
  - Flatten:
      name: HEmbedding
  - Concatenate:
      input: [HEmbedding,PEmbedding]
  - Dense:
      name: mixture_embedding
      units: 1024
      activation: relu
      use_bias: False
      dropout: 0.5
      batch_norm: True
  #Shared deconvolution layers:
  - Conv:
      input: unconnected
      name: h_vdeconv
      transpose: True
      filters: 32
      kernel_size: [82,1]
      strides: [41,1]
      activation: relu
  - Conv:
      input: unconnected
      name: h_hdeconv
      transpose: True
      filters: 2
      kernel_size: [1,21]
      activation: relu
  - Conv:
      input: unconnected
      name: p_hdeconv
      transpose: True
      filters: 64
      kernel_size: [1,6]
      activation: relu
  - Conv:
      input: unconnected
      name: p_vdeconv
      transpose: True
      filters: 2
      kernel_size: [1025,1]
      activation: relu
  - BlockDefinition:
      input: unconnected
      name: dual_decoder
      block_in: [p_separator,h_separator]
      block:
      - Dense:
          name: p_separator
          units: 1024
          activation: relu
      - Reshape:
          name: p_reshape
          target_shape: [1,16,64]
      - SharedLayer:
          name: p_hdeconv
          layer: p_hdeconv
      - SharedLayer:
          name: p_vdeconv
          layer: p_vdeconv
      - Expression:
          name: p_invlog2p1
          expr: 2**x-1
      - Dense:
          name: h_separator
          units: 1536
          activation: relu
      - Reshape:
          name: h_reshape
          target_shape: [24,1,64]
          input: h_separator
      - SharedLayer:
          name: h_vdeconv
          layer: h_vdeconv
      - SharedLayer:
          name: h_hdeconv
          layer: h_hdeconv
      - Expression:
          name: h_invlog2p1
          expr: 2**x-1
      - Add:
          input: [h_invlog2p1, p_invlog2p1]
  - Block:
      input: mixture_embedding
      name: bass_decoder
      block: dual_decoder
  - Block:
      input: mixture_embedding
      name: drums_decoder
      block: dual_decoder
  - Block:
      input: mixture_embedding
      name: others_decoder
      block: dual_decoder
  - Block:
      input: mixture_embedding
      name: vocals_decoder
      block: dual_decoder
  - Stack:
      input: [bass_decoder, drums_decoder, others_decoder, vocals_decoder]
      name: all_sources
      axis: 1
  - SoftMask:
      input: [all_sources,mixture_spectrogram]
      name: masked_mag
  inputs: [mixture_spectrogram]
  outputs: [masked_mag]